apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-root-volume
  labels:
    type: aws-ebs-volume
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: vol-sampleid233
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  labels:
    type: aws-ebs-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
