apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busapp-vo1-pvc
  namespace: develop
spec:
  resources:
   requests:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: gp2
